version: "3"
services:
  dscytbot:
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ./app:/app
      - ./downloads:/app/downloads
    environment:
      PUBLIC_ADDRESS: ${PUBLIC_ADDRESS}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      QUIET: ${QUIET}
    # restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./downloads:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:5000:80"
    # restart: always
