version: "3"
services:
  dsc-yt-bot:
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - .:/app
    environment:
      PUBLIC_ADDRESS: "YourPublicWebAddressHere"
      DISCORD_TOKEN: "YourDiscordBotTokenHere"
      QUIET: "true"
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./downloads:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    restart: always
